# Generated by Django 4.2.3 on 2024-12-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('responsible_part', models.CharField(blank=True, choices=[('KANAT', 'Kanat'), ('GÖVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVİYONİK', 'Aviyonik'), ('MONTAJ', 'Montaj')], max_length=20, null=True)),
            ],
        ),
    ]
